name: Label Pull Request Contributors

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  label-contributor:
    runs-on: ubuntu-latest
    steps:
      - name: Label PR based on contributor membership
        uses: actions/github-script@v7
        with:
          script: |
            try {
              // Check if the PR author is a member of GENWAY-AI organization
              const { data: membership } = await github.rest.orgs.checkMembershipForUser({
                org: 'GENWAY-AI',
                username: context.payload.pull_request.user.login
              });
              
              // Organization member - add internal label
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                labels: ['internal-contributor']
              });
              
              console.log(`✅ PR from organization member: ${context.payload.pull_request.user.login}`);
              
            } catch (error) {
              // Not an organization member (or membership is private) - add external label
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                labels: ['external-contributor']
              });
              
              // Welcome external contributors with helpful message
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                body: '👋 Welcome External Contributor! Thank you for your contribution to youtube-link-utils! Your PR will be reviewed by GENWAY-AI organization members before merging.'
              });
              
              console.log(`🔍 PR from external contributor: ${context.payload.pull_request.user.login}`);
            }
