name: Release & Publish

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 1.0.1)'
        required: true
        type: string

jobs:
  release:
    name: Release & Publish to NPM
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Run full test suite
        run: |
          npm run quality
          npm test

      - name: Run security audit
        run: |
          npm audit --audit-level moderate
          npx audit-ci --moderate

      - name: Build package
        run: npm run build

      - name: Validate package structure
        run: |
          # Verify all expected files exist
          test -f dist/index.js
          test -f dist/index.cjs
          test -f dist/index.d.ts
          test -f dist/react/index.js
          test -f dist/react/index.cjs
          test -f dist/react/index.d.ts

          npm pack --dry-run

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ github.ref_name }}
          body: |
            🎉 New release of youtube-link-utils!

            **Version:** ${{ github.ref_name }}
            **Published:** $(date -u)

            ## 📋 Changes
            See [CHANGELOG.md](https://github.com/GENWAY-AI/youtube-link-utils/blob/main/CHANGELOG.md) for details.

            ## 📦 Installation
            ```bash
            npm install @genway-ai/youtube-link-utils@${{ github.ref_name }}
            ```
          draft: false
          prerelease: false
